import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tasnim Alam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-4 min-h-screen">
      <body className={inter.className}>
        
        <nav>
          <ul className="flex gap-5">
            <li><Link href="/"> Home</Link> </li>
            <li><Link href="/about"> About</Link> </li>
            <li><Link href="/blogs"> Blogs</Link> </li>
 
          </ul>
        </nav> <hr/>
        {children}</body>
    </html>
  );
}
